// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Files 是暴露给前端的核心服务：文件对话框、读取、配置、草稿、贴图、多窗口
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AllowDir 把目录加入 /kfs 白名单（打开文档 / 加载用户主题时调用）
 */
export function AllowDir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(2747285133, dir);
}

/**
 * AppVersion 返回应用版本号，供插件 API 判断兼容性
 */
export function AppVersion(): $CancellablePromise<string> {
    return $Call.ByID(1909390684);
}

/**
 * AuthorizePath 前端打开文档前调用：仅放行落在 /kfs 白名单目录内的路径
 * （用户已明确打开过该目录），防止被注入的 JS 借授权接口扩权。
 */
export function AuthorizePath(path: string): $CancellablePromise<void> {
    return $Call.ByID(3635465219, path);
}

export function ConfigDir(): $CancellablePromise<string> {
    return $Call.ByID(4085185426);
}

/**
 * DeleteDraft 删除草稿（保存成功 / 用户明确放弃后）
 */
export function DeleteDraft(forPath: string): $CancellablePromise<void> {
    return $Call.ByID(2357780261, forPath);
}

/**
 * InitialFile 返回一个通过文件关联传入的待打开 Markdown 文件路径。
 * 读取后会消费该路径，避免前端重复打开。
 */
export function InitialFile(): $CancellablePromise<string> {
    return $Call.ByID(477854545);
}

export function ListExternalPlugins(): $CancellablePromise<$models.ExternalPlugin[] | null> {
    return $Call.ByID(2845488314);
}

/**
 * ListUserThemes 扫描 themes/<id>/theme.json 的用户主题包
 */
export function ListUserThemes(): $CancellablePromise<({ [_ in string]?: any } | null)[] | null> {
    return $Call.ByID(3897320936);
}

/**
 * LoadDraft 读取草稿；不存在（或已损坏）返回 nil
 */
export function LoadDraft(forPath: string): $CancellablePromise<$models.DraftInfo | null> {
    return $Call.ByID(4216744132, forPath);
}

/**
 * MarkFrontendReady 标记前端已注册第二实例事件，并返回启动期间积压的路径。
 */
export function MarkFrontendReady(): $CancellablePromise<string[] | null> {
    return $Call.ByID(4231233799);
}

/**
 * OpenNewWindow 拖出标签：以 --multi 启动一个独立窗口进程展示该文档
 */
export function OpenNewWindow(path: string): $CancellablePromise<void> {
    return $Call.ByID(3710771641, path);
}

export function PickFile(): $CancellablePromise<string> {
    return $Call.ByID(1051436290);
}

/**
 * QuitApp 前端确认（或无未保存修改）后调用，真正退出
 */
export function QuitApp(): $CancellablePromise<void> {
    return $Call.ByID(3732008241);
}

/**
 * ReadConfig 读取 config.json；不存在时返回空 map（不报错）
 */
export function ReadConfig(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(599910739);
}

/**
 * ReadFile 读取文件内容（限制 16MB）；UTF-8 优先，旧中文文档回退 GB18030 解码。
 * 仅允许读取会话授权过的路径（用户打开/保存过的文件）。
 */
export function ReadFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(1735965079, path);
}

/**
 * ReadPluginCode 读取插件入口脚本 main.js
 */
export function ReadPluginCode(id: string): $CancellablePromise<string> {
    return $Call.ByID(3677350635, id);
}

/**
 * RevealPath 在资源管理器中定位文件/文件夹（仅授权路径或白名单目录内）
 */
export function RevealPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(4212949547, path);
}

/**
 * SaveAsPath 弹出保存对话框，返回用户选择的路径
 */
export function SaveAsPath(name: string): $CancellablePromise<string> {
    return $Call.ByID(245211123, name);
}

/**
 * SaveClipboardImage 把 base64 图片写入 dir/name，返回完整路径。
 * dir 必须在 /kfs 白名单目录内；name 强制取 Base（防 ..\ 穿越）且仅限图片扩展名。
 */
export function SaveClipboardImage(dir: string, name: string, b64: string): $CancellablePromise<string> {
    return $Call.ByID(1062785383, dir, name, b64);
}

/**
 * SaveConfig 增量合并写入：前端只发变化字段，这里与磁盘现有配置合并，
 * 避免多进程（--multi 拆窗）互相用旧状态全量覆盖。原子写入防损坏。
 */
export function SaveConfig(cfg: { [_ in string]?: any } | null): $CancellablePromise<void> {
    return $Call.ByID(2444243906, cfg);
}

/**
 * SaveDraft 落盘未保存内容快照（前端 dirty 时防抖调用）
 */
export function SaveDraft(forPath: string, name: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(1844657095, forPath, name, content);
}

/**
 * SaveHtmlPath 导出 HTML 的保存对话框
 */
export function SaveHtmlPath(name: string): $CancellablePromise<string> {
    return $Call.ByID(1106689770, name);
}

/**
 * WriteFile 保存文件内容（原子写入）；仅授权路径且限文本类扩展名
 */
export function WriteFile(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3306767214, path, content);
}
