// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DraftInfo 一次未保存内容的快照（%APPDATA%/KairosMd/drafts/）
 */
export interface DraftInfo {
    /**
     * 对应文档路径，未命名文档为空串
     */
    "for": string;
    "name": string;
    "content": string;

    /**
     * 毫秒时间戳
     */
    "t": number;
}

/**
 * ExternalPlugin 磁盘上的外部插件（%APPDATA%/KairosMd/plugins/<id>/）
 */
export interface ExternalPlugin {
    "id": string;
    "manifest": { [_ in string]?: any } | null;
    "hasMain": boolean;
}
