// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppVersion():Promise<string>;

export function ConfigDir():Promise<string>;

export function DeleteDraft(arg1:string):Promise<void>;

export function InitialFile():Promise<string>;

export function ListExternalPlugins():Promise<Array<main.ExternalPlugin>>;

export function ListUserThemes():Promise<Array<Record<string, any>>>;

export function LoadDraft(arg1:string):Promise<main.DraftInfo>;

export function MarkFrontendReady():Promise<Array<string>>;

export function PickFile():Promise<string>;

export function QuitApp():Promise<void>;

export function ReadConfig():Promise<Record<string, any>>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadPluginCode(arg1:string):Promise<string>;

export function RevealPath(arg1:string):Promise<void>;

export function SaveAsPath(arg1:string):Promise<string>;

export function SaveClipboardImage(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveConfig(arg1:Record<string, any>):Promise<void>;

export function SaveDraft(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveHtmlPath(arg1:string):Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
