// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppVersion() {
  return window['go']['main']['Files']['AppVersion']();
}

export function ConfigDir() {
  return window['go']['main']['Files']['ConfigDir']();
}

export function DeleteDraft(arg1) {
  return window['go']['main']['Files']['DeleteDraft'](arg1);
}

export function InitialFile() {
  return window['go']['main']['Files']['InitialFile']();
}

export function ListExternalPlugins() {
  return window['go']['main']['Files']['ListExternalPlugins']();
}

export function ListUserThemes() {
  return window['go']['main']['Files']['ListUserThemes']();
}

export function LoadDraft(arg1) {
  return window['go']['main']['Files']['LoadDraft'](arg1);
}

export function MarkFrontendReady() {
  return window['go']['main']['Files']['MarkFrontendReady']();
}

export function PickFile() {
  return window['go']['main']['Files']['PickFile']();
}

export function QuitApp() {
  return window['go']['main']['Files']['QuitApp']();
}

export function ReadConfig() {
  return window['go']['main']['Files']['ReadConfig']();
}

export function ReadFile(arg1) {
  return window['go']['main']['Files']['ReadFile'](arg1);
}

export function ReadPluginCode(arg1) {
  return window['go']['main']['Files']['ReadPluginCode'](arg1);
}

export function RevealPath(arg1) {
  return window['go']['main']['Files']['RevealPath'](arg1);
}

export function SaveAsPath(arg1) {
  return window['go']['main']['Files']['SaveAsPath'](arg1);
}

export function SaveClipboardImage(arg1, arg2, arg3) {
  return window['go']['main']['Files']['SaveClipboardImage'](arg1, arg2, arg3);
}

export function SaveConfig(arg1) {
  return window['go']['main']['Files']['SaveConfig'](arg1);
}

export function SaveDraft(arg1, arg2, arg3) {
  return window['go']['main']['Files']['SaveDraft'](arg1, arg2, arg3);
}

export function SaveHtmlPath(arg1) {
  return window['go']['main']['Files']['SaveHtmlPath'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['Files']['WriteFile'](arg1, arg2);
}
